### ISSUE TITLE
Error because of empty Title in Pronouns Setup window

### ISSUE THREAD

**Issue by Paukler** [vtt-lair/player-pronouns#18]
When i try and click "Add Pronouns" or delete a pronoun (aka call the render function) it shows me an error.
And after which the window isnt usable anymore:
![Screenshot 2022-09-01 172709](https://user-images.githubusercontent.com/25936043/187955494-91e9f878-c4b9-4953-af15-50a1f0dfe69e.png)
![Screenshot 2022-09-01 172720](https://user-images.githubusercontent.com/25936043/187955504-d780f518-6608-413e-bcd6-89664b0ddb6f.png)

After trying a few things out i found just adding a title to the window works without a problem:
![Screenshot 2022-09-01 172800](https://user-images.githubusercontent.com/25936043/187955790-b69a7983-7523-41c3-9759-a655b765c340.png)
![Screenshot 2022-09-01 172833](https://user-images.githubusercontent.com/25936043/187955793-d08b2a95-cfbb-4035-a779-ed943d7a190d.png)
![Screenshot 2022-09-01 172844](https://user-images.githubusercontent.com/25936043/187955800-172b9828-0591-415c-8a6f-e31699b6ad0b.png)

**Comment by vtt-lair** [comment]
@Paukler thanks for the detailed analyses and debugging. I'll have this fix in by tomorrow night... I never tested the setup screen in version 10 :(

**Comment by vtt-lair** [comment]
@Paukler new release has been made with the fix. Thanks again!
