### ISSUE TITLE
Could there be a way to distinguish between player pronouns and character pronouns?

### ISSUE THREAD

**Issue by Bolt7** [vtt-lair/player-pronouns#4]

**Comment by vtt-lair** [comment]
@Bolt7 Currently there is no way, I have it however as a future development to implement the pronouns on the tokens as well. 

At the moment still investigating whether it will be sitting on the Actor or on the Token or on both.

**Comment by Bolt7** [comment]
If/when you implement character pronouns, it might be good to know that the Pathfinder 2e sheet has a pronouns section, and at least for that system it would be very convinient to use that as the character's pronouns.

**Comment by vtt-lair** [comment]
@Bolt7 character pronouns has been release on v.0.1.4. There is also functionality to pull it to the Gender/Pronoun field on the actor. Has been test on 5e systems as well as PF2e.
